### ISSUE TITLE
增加一个has函数，修改事件支持返回参数

### ISSUE THREAD

**Issue by meystack** [webman-php/event#1]
`    /**
     * @param string $name
     * @return void
     */
    public static function has(string $name)
    {
        $list = static::list();

        foreach ($list as $index => $item) {
            if ($item[0] == trim($name)) {
                return true;
            }
        }

        return false;
    }`
`    /**
     * @param $event_name
     * @param $data
     * @return
     */
    public static function emit($event_name, $data, $once = false)
    {
        $success_count = 0;
        $callbacks = static::$eventMap[$event_name]??[];
        foreach (static::$prefixEventMap as $name => $callback_items) {
            if (strpos($event_name, $name) === 0) {
                $callbacks = array_merge($callbacks, $callback_items);
            }
        }
        ksort($callbacks);
        $ret = [];
        foreach ($callbacks as $callback) {
            try {
                $ret[$event_name] = $callback($data, $event_name);
                $success_count++;
            } catch (\Throwable $e) {
                if (!static::$logger && is_callable('\support\Log::error')) {
                    static::$logger = Log::channel();
                }
                if (static::$logger) {
                    static::$logger->error($e);
                }
                continue;
            }
        }

        if ($once && isset($ret[$event_name])) {
            return $ret[$event_name];
        }

        return $ret;
    }`

默认事件不返回钩子调用的数据，无法满足某些场景，另外返回false会终止，
增加了一个has的函数检查当前钩子是否存在

**Comment by walkor** [comment]
主干已经添加
