### ISSUE TITLE
emit 函数修改

### ISSUE THREAD

**Issue by meystack** [webman-php/event#2]
@walkor 默认的函数

    public static function emit($event_name, $data, $halt = false)
    {
        $success_count = 0;
        $listeners = static::getListeners($event_name);
        $responses = [];
        foreach ($listeners as $listener) {
            try {
                $response = $listener($data, $event_name);
            } catch (\Throwable $response) { **// 这里写错了**
                if (!static::$logger && is_callable('\support\Log::error')) {
                    static::$logger = Log::channel();
                }
                if (static::$logger) {
                    static::$logger->error($e); // **$e?** 
                }
                continue;
            }

            $responses[] = $response;
            if ($halt && !is_null($response)) {
                return $response;
            }
           // 如果一个userLogin存在两个钩子
          // 第一个返回false就中断执行了，
            if ($response === false) {
                break;
            }
        }
        return $halt ? null : $responses;
    }

其他的没发现异常可以正常调用回显！可以合并后发一个版本！

**Comment by walkor** [comment]
异常的改好了，
return false 中断执行这个就是这样设计的。

**Comment by meystack** [comment]
如果同一个钩子有多个事件类去执行他的操作，第一个返回false的时候，比如异常了，或者出现其他BUG了，
那第二个钩子就无法执行了啊，这样直接中断了，基于什么考虑的呢？

**Comment by meystack** [comment]
@walkor 顺便想问下 webman1.4版本发布后 对于控制器构造函数，也就是=》是否复用控制器配置这个来替代action-hook方案
后期是否还会改变？是否可以确定您当前的这个方案是稳定可行的，因为要开发一部分插件，怕写完后，后期webman迭代，再去更新就麻烦了！
